name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create local.properties
        run: |
          touch ./local.properties
          echo "${{ secrets.LOCAL_PROPERTIES }}" >> ./local.properties
        shell: bash

      - name: Access BASE_URL
        run: |
          echo BASE_URL=\"$BASE_URL\" > ./local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.BASE_URL }}

      - name: Access REFRESH_API_URL
        run: |
          echo REFRESH_API_URL=\"$REFRESH_API_URL\" > ./local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.REFRESH_API_URL }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
