name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create local.properties
          run: |
            touch ./local.properties
            echo "${{ secrets.BASE_URL }}" >> ./local.properties
          shell: bash

      - name: Create local.properties
          run: |
            touch ./local.properties
            echo "${{ secrets.REFRESH_API_URL }}" >> ./local.properties
          shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
